version: "1.0"
name: knowgraph
languages:
  - typescript
include:
  - "packages/*/src/**/*"
exclude:
  - node_modules
  - dist
  - .git
  - .turbo
  - coverage
  - __tests__
  - "*.test.ts"
  - "*.spec.ts"
index:
  output_dir: .knowgraph
  incremental: true
